sonata_admin:
    title: 'Green-World'
    title_logo: /bundles/sonataadmin/logo2.png
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

    templates:
        dashboard: 'dashboard2.html.twig'
        user_block: 'user_block2.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
